[package]
name = "quicktok"
version = "0.1.0"
edition = "2021"

[lib]
name = "quicktok"
crate-type = ["cdylib", "lib"]

[dependencies]
indexmap = "2.2.3"
pyo3 = "0.20.3"
rayon = "1.8.1"
tempfile = "3.10.0"
