[package]
name = "quicktok-examples"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "train"

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
reqwest = { version = "0.11.24", features = ["blocking"] }
zip = "0.6.6"

quicktok = { path = "../quicktok" }
